version: "3.3"
services:
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./database-data:/data/db