---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-deliveries
  namespace: egs2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi